### ISSUE TITLE
Java loading problem

### ISSUE THREAD

**Issue by Maiker404** [fribbels/Fribbels-Epic-7-Optimizer#163]
Even though I have installed a new version of Java and put its path in the environment variables and also the "JAVA_HOME" the application continues to present me with this problem!

![image](https://user-images.githubusercontent.com/36998496/175318169-d05901d2-d412-4744-852a-3c7327829666.png)

**Comment by Dalkil** [comment]
I have the same problem, although I get a different description. I don't know if it's due to the new version released or because I installed the program on a new computer (it worked perfectly, at least until previous version a couple days ago). In any case, after running the exe, Microsoft Store opens and direct me to Phython 3.7 (I downloaded it, but the problem is still there). 

Could someone please help? 


![Problem](https://user-images.githubusercontent.com/63915320/175612597-956f376c-1d25-46a8-85ee-8022bbbadc28.jpg)

**Comment by rascboy** [comment]
I'm having a similar issue with it not seeing my Java installation as well. Reinstalled multiple times and have ensured the ENV PATH is set. Interestingly, I can click OK and I'm able to open my emulator/epic7 and pull the gear data into the gear.txt file but when I try to merge the data into Fribbels, I see more errors. I've opened up the dev console and see a bunch of errors as well. Both screenshots posted below:

![image](https://user-images.githubusercontent.com/6312454/179554700-63e837bf-78e3-438b-a6dc-ef59cd381d62.png)

![image](https://user-images.githubusercontent.com/6312454/179554766-65b38c45-c27f-45eb-a658-3a1d347451bf.png)

**Comment by Delgathar** [comment]
I have the same problem, I think.  I updated Java when I first saw the window but the problem didn't go away.  My secondary problem is the window only flashes and dissapears so there is no way to read it all, I just saw the word Java in there after repeated tries and staring hard.  Please make the alert window stay open until I hit ok.

**Comment by AJustinWilson** [comment]
Same issue anyone find a fix?

**Comment by Maiker404** [comment]
> Same issue anyone find a fix?
> 
> Edit: I ended up fixing the issue by following this https://mkyong.com/java/how-to-set-java_home-on-windows-10/

Thanks for the manual on how to do JAVA_HOME the right way!

Obs.: If anyone who has the same problem does the step by step of the manul, make sure that the PATH of "%JAVA_HOME%/bin" is the only one being referenced, if you have the JRE being referenced, the PATH will occur wrath for him is not for the JDK!
