### ISSUE TITLE
some units icons fail to load

### ISSUE THREAD

**Issue by vastablack** [fribbels/Fribbels-Epic-7-Optimizer#177]
I don't know what's causing this issue, I tried to reinstall everything and erased all data but still face the same issue, also disabled GPU optimization
some units icons just fail to load 
![un2known](https://user-images.githubusercontent.com/116946331/198824138-50ef4bd5-5251-46bd-b3df-d3a8330d073b.png)

**Comment by vastablack** [comment]
fixed by new update

**Comment by vastablack** [comment]
dunno wat happned over night but sadly its back again x_x

**Comment by Joy97D** [comment]
Same some icons fail to load :(

**Comment by jmferreirab** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**What have you tried**
Uninstall / format / change network adapter / etc...

**System information:**
 - OS: [e.g. iOS]
 - Admin / Non admin user
 - Fribbles Version

**Additional context**
Add any other context about the problem here.

1. Can you please provide an update on your status for this issue? If possible also, please fix your original post to include relevant bug information.

2. Does only Adin image show? Does it happen in all other panels? Optimizer? Gear?

3. Can you check also if you are getting any error messages in the console and paste if relevant? Ctrl-Shift-I opens the console in Fribbles.
