### ISSUE TITLE
Errors when importing from Zarroc

### ISSUE THREAD

**Issue by aelhaik** [fribbels/Fribbels-Epic-7-Optimizer#18]
[Backup.zip](https://github.com/fribbels/Fribbels-Epic-7-Optimizer/files/5953395/Backup.zip)

Getting a bunch of errors when importing. Looks like gear comes through but heroes don't show up at all.

**Comment by fribbels** [comment]
I tested it on the 1.4 version coming out in a couple days and it looks fine to me.

Was able to see all your units/gear the same as the zarroc version:

![https://i.imgur.com/elvgBWa.png](https://i.imgur.com/elvgBWa.png)

![https://i.imgur.com/mcqjuDj.png](https://i.imgur.com/mcqjuDj.png)

Im attaching an export of the same data, in case that helps, otherwise please hold on until the 1.4 release.

[aelhaik-export.zip](https://github.com/fribbels/Fribbels-Epic-7-Optimizer/files/5958120/aelhaik-export.zip)

**Comment by aelhaik** [comment]
Export works perfectly.

Thank you.
