### ISSUE TITLE
Temporary fix for auto-scanner failing to read items

### ISSUE THREAD

**Issue by fribbels** [fribbels/Fribbels-Epic-7-Optimizer#50]
The previous fix has been released in v1.6. Still investigating other causes.

See: https://github.com/fribbels/Fribbels-Epic-7-Optimizer/issues/50#issuecomment-803039064

**Comment by Huasenberg** [comment]
The fix works! Thanks (From Bluestacks)

**Comment by kfisher723** [comment]
Unfortunately still no luck for me with this version

**Comment by fribbels** [comment]
> Unfortunately still no luck for me with this version

Could you open the dev tools, go to the Console tab and scroll down, run a scan, and then screenshot the console tab? Lets see if there are other issues on your side.

![https://i.imgur.com/4m56hDu.png](https://i.imgur.com/4m56hDu.png)
![https://i.imgur.com/rD8KquG.png](https://i.imgur.com/rD8KquG.png)

**Comment by marioteik** [comment]
Not working for me too, even with the new file:

![image](https://user-images.githubusercontent.com/6776658/111035183-02fa0580-83f8-11eb-8f22-9b19d1c21c71.png)

**Comment by fribbels** [comment]
> Not working for me too, even with the new file:

Everything looks installed fine on your side, unfortunately the current scanner doesn't work for some peoples' networks. Still investigating, sorry about that

**Comment by marioteik** [comment]
No need to apologize, man.
You're doing a really awesome work!
Thank you for helping the community. <3

**Comment by Kammuzz** [comment]
@fribbels 
After following all the steps the error continues. I will put the photo here to try to help the developers to identify the problem.
I tested it on MumuPlayer and Bluestacks4.

![Scan failed](https://user-images.githubusercontent.com/80802308/111408568-3a94d600-86b4-11eb-865b-f8b684028987.png)

**Comment by JooeeMin** [comment]
@fribbels 

Downloading new python.py file got the item reading to work. It's been 15 minutes and it is still

"Reading items, this may take up to 30 seconds...
Data will appear here after it is done."

Any ideas?

Thanks! :)

**Comment by fribbels** [comment]
You probably fall under the category of users whose networks the scanner doesn't work on. Try it a few more times, otherwise I don't have an answer yet

**Comment by marioteik** [comment]
@fribbels can you share with me what a healthy log should look like? If you want I can try do debug check what is the problem.

**Comment by Pacman2k** [comment]
fwiw, scanner was working fine for me and i upgraded bluestacks and now it's broken and has same error behavior as shown above from @marioteik - I am now on 4.260.4207 and am not sure what version i was on previously

i grabbed my laptop (on the same network) and am able to successfully scan there - so, at least in my case this seems like a local PC configuration issue not a network one.  ill try downgrading bluestacks if i can figure out how and see if that solves it.

**Comment by fribbels** [comment]
Can either of you add me on discord at fribbels#7526? Would be easier to debug that way

**Comment by marioteik** [comment]
![image](https://user-images.githubusercontent.com/6776658/111775528-a54e3900-888f-11eb-8776-c617622fd137.png)

I could import everything with my mobile plugged on a hotspot in my computer. I have bluestacks for hyper-v, so that could be a problem. I will add you on discord so you can check for yourself.

**Comment by Pacman2k** [comment]
this does seem to be related to hyper-v and the new network adapter it sets up.  workaround would be not to use hyper-v bluestacks.

i'm also able to work around this by hardcoding a single adapter (via adapter GUID) to scan on in the python script - but this method will be different for each person who wants to use it so is not a viable solution to post here.

**Comment by Pacman2k** [comment]
hi all - since this is popping up on discord I wanted to document my workaround steps real quick:

1. Obtain the GUID of the network adapater you use for your Host PC to connect to the network.  You can obtain this information by opening Regedit and navigating to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkCards\ - Each of your network adapters will be listed here in numerical order - select the one that represents your active network connection and retrieve the GUID from the "ServiceName" key - it should look something like this:  **{44539183-C457-4441-97A0-DE90293B1509}**

2. Open scanner.py in a text editor from the data/py/ directory within your Fribbels directory.

3. Edit the thread_sniff function to contain a hardcoded requirement to only scan on the GUID you selected above - I did this:

`def thread_sniff(i, index):
    try:
        sniff(iface=i, prn=lambda x: check_packet(x, index), filter="tcp and ( port 3333 )")
    except:
        pass

index = 0
for i in list(conf.ifaces.data.values()):
    if (i == '\\Device\\NPF_{44539183-C457-4441-97A0-DE90293B1509}'):
        #print (i)
        try:
            x = threading.Thread(target=thread_sniff, args=(i, index,))
            x.daemon = True;
            x.start()

            index = index + 1
        except:
            pass
    else:
        pass
        #print ("nope")
`

After doing the above I was able to scan as normal while using Hyper-V Bluestacks.

**Comment by fribbels** [comment]
Additional information for Hyper-V users: 

> The instructions for Hyper-V didn't mention which system to pull the NIC number from. I don't use E7 in Hyper-V, just on the Hyper-V host.  You cannot do pass through on the virtual switch so basically I had to go into my VM and check that same place in regedit to get the number and edit the scanner.py outside the VM.

**Comment by MichFe** [comment]
This is still happening on new version when user have more than 1 GUID.

**Comment by jmferreirab** [comment]
> This is still happening on new version when user have more than 1 GUID.

You will need to either:

- 1. Follow the instructions here: https://github.com/fribbels/Fribbels-Epic-7-Optimizer/issues/50#issuecomment-804275567

- 2. Or take the file below to replace the one you have at C:\Program Files\FribbelsE7Optimizer\data\py\scanner.py.

At this time, this is a process that needs to be done every update for affected users.

https://github.com/jmferreirab/Fribbels-Epic-7-Optimizer/blob/f85ec6c9d84ba32329e31247251e67283fd48dc4/data/py/scanner.py
