### ISSUE TITLE
Issue: "Prio" filter uses gear sets with overcapped stats

### ISSUE THREAD

**Issue by Severinus3** [fribbels/Fribbels-Epic-7-Optimizer#82]
I love the idea of the new Priority filter for overall value in all desired stats, but it includes stats that go over cap, most notable being Crit Rate. My highest Prio gear set has 150% crit rate for example

**Comment by fribbels** [comment]
Ah yea I see what you mean - prio is meant as a window into how the substat priority filter works though, since it directly takes the priority scores of the 6 items and adds them together so I'm not sure if it would make sense to cap certain stats for that score. For your case though, I think you could set a max crit rate limit on the stat filters if you wanted to avoid those 150% crit builds for example

**Comment by Severinus3** [comment]
Totally forgot I can do that :P Will do, thanks!
